<?php echo $header; ?>
<div class="breadcrumbs">
  <div class="container">
      <div class="title-breadcrumb">
        <?php $count = count($breadcrumbs);?>
        <?php $i=0; ?>
        <?php foreach ($breadcrumbs as $breadcrumb) { ?>
            <?php if( $i == $count-1){ ?>
               <?php echo '<b>'.$breadcrumb['text'].'</b>'; ?>
            <?php }else{ ?>
              <a href="<?php echo $breadcrumb['href']; ?>"></a>
            <?php } ?>
          <?php $i++; ?>
        <?php } ?>
      </div>
      <ul class="breadcrumb-cate">
          <?php foreach ($breadcrumbs as $breadcrumb) { ?>
          <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
          <?php } ?>
      </ul>
  </div>
</div>
<div class="container">

  <div class="row"><?php echo $column_left; ?>
    <?php if ($column_left && $column_right) { ?>
    <?php $class = 'col-sm-6'; ?>
    <?php } elseif ($column_left || $column_right) { ?>
    <?php $class = 'col-md-9'; ?>
    <?php } else { ?>
    <?php $class = 'col-sm-12'; ?>
    <?php } ?>
    <div id="content" class="<?php echo $class; ?>"><?php echo $content_top; ?>
      <div class="row">
          <div class="col-sm-12">
            <div class="well">
              <h3>Seller Terms & Conditions</h3>
              <p>
            	<p>This Privacy Policy (“
            		<strong>Policy</strong>“) is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. The Policy is an ‘electronic record’ as contemplated under section 2(t) of the Information Technology&nbsp;Act, 2000 and the rules. This Policy being an electronic record is generated by a computer system and does not require any physical or digital signature.
            		<br>
            		</p>
            		<p>The website&nbsp;www.sezplus.com("
            			<strong>Website</strong>") is operated by RK SEZPLUS Services Pvt Ltd, a company incorporated under the laws of India having its registered office at Mumbai.
            		</p>
            		<br>
            			<p> We value the trust you place in us. That's why we insist upon the highest standards for secure transactions and customer information privacy. Please read the following statement to learn about our information gathering and dissemination practices.</p>
            			<p>Note:
            				<br> Our privacy policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically.
            					<br>
            						<br> By visiting this Website you agree to be bound by the terms and conditions of this Privacy Policy. If you do not agree please do not use or access our Website.
            							<br>
            								<br> By mere use of the Website, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms of Use
            									<br>
            									</p>
            									<p>&nbsp;</p>
            									<p>USER INFORMATION</p>
            									<p>‘User information’ for the purpose of this Policy includes the user’s personal information that can be used to uniquely identify or contact a single person including name, email address, &nbsp;residential address, phone number, photograph and other information collected by sezplus to provide specific services to the user through the Website. The user has the option not to provide User Information if the user wishes not to avail the specific service for which the User Information is required.&nbsp;
                          </p>
            									<p>If any user is providing any User Information on behalf of any corporation, company, institution, association or other entity, the user should be authorized by such corporation, company, institution, association or other entity to provide such information to sezplus.</p>
            									<p>SEZPLUS collects information from the user when creating a user account or when the user is browsing for products, transacting an online purchase of products through the Website or while posting comments, uploading content or participating in any offers or contests or availing special gifts or communicating with customer support by phone, email or otherwise.&nbsp;</p>SEZPLUS receives, scrutinizes and stores User Information for security and technical reasons such as IP address, login id, email address, password, devise connection information transaction history, date, time and duration of session on the Website.&nbsp;


            								</p>
            								<p>
            									<p>sezplus automatically receives the URL of the site from which a user came and the site to which the user goes when the user leaves the Website. The Website receives the IP address of the user’s computer and the type of web browser a user is using, email patterns, etc. sezplus will occasionally ask the user to complete optional online surveys. These surveys may ask the user for contact information and demographic information (eg. zip code, age or income level).</p>
            									<p>Sometime the Website uses cookies so that the Website can provide the user with more customize information when the user returns to the Website. "Cookies" are used to store user preferences and to track user trends, so as to enhance the user’s interactive experience and generally improve the Website’s services to the user. The user can set the browser to notify the user when the user is sent a "cookie", giving the user the chance to decide whether or not to accept it. If the user accepts a "cookie", the user agrees to the use of any User Information collected by the Website using that cookie. The user may update the profile information of the user at any time on the Website.</p>
            									<p>&nbsp;</p>
            									<p>The user can add or update the User Information on a regular basis. When the user updates the User Information, sezplus will keep a copy of the prior version for its records.
            										<br>
            											<br> COLLECTION OF PERSONALLY IDENTIFIABLE INFORMATION AND OTHER INFORMATION
            											</p>
            											<p>When you use our Website, we collect and store your personal information which is provided by you from time to time. Our primary goal in doing so is to provide you a safe, efficient, smooth and customized experience. This allows us to provide services and features that most likely meet your needs, and to customize our Website to make your experience safer and easier. More importantly, while doing so we collect personal information from you that we consider necessary for achieving this purpose.
            												<br>
            													<br> In general, you can browse the Website without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information by choosing not to use a particular service or feature on the Website. We may automatically track certain information about you based upon your behaviour on our Website. We use this information to do internal research on our users' demographics, interests, and behaviour to better understand, protect and serve our users. This information is compiled and analysed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Website or not), which URL you next go to (whether this URL is on our Website or not), your computer browser information, and your IP address.
            														<br>
            															<br> If you choose to buy on the Website, we collect information about your buying behaviour.
            																<br>
            																	<br> If you transact with us, we collect some additional information, such as a billing address, a credit / debit card number and a credit / debit card expiration date and/ or other payment instrument details and tracking information from cheques or money orders.
            																		<br>
            																			<br> If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback, we will collect that information you provide to us. We retain this information as necessary to resolve disputes, provide customer support and troubleshoot problems as permitted by law.
            																				<br>
            																					<br> If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Website, we may collect such information into a file specific to you.
            																					</p>
            																					<p>USE OF INFORMATION &amp; DISCLOSURE</p>
            																					<p>The User Information is primarily used by sezplus to facilitate a better, customized and convenient use of the Website’s services. The User Information is used by sezplus inter alia to (i) respond to the user’s queries, requests and &nbsp;inquiries; (ii) update new features of the Website, (iii) improve and customize the Website’s service, (iv) detect and prevent fraud and abuse of the Website, (v) examine the identity of the user’s and the authenticity of offers, delivery or transfer of offers, etc. (vi) administer the Website, (vii) inform any change in the Terms of Use or this Policy or the Terms and Conditions of Sale,&nbsp;(viii) send surveys and marketing communications that sezplus believes may be of interest to the user; (ix) personalize the user’s experience on the Website by presenting advertising, products and offers tailored for the user; (x) help the user address its problems with the Website including addressing any technical problems; &nbsp;(xi) &nbsp;complete and fulfill the user’s purchase, process payments, communicate with the user regarding the user’s purchase and provide the user with related customer service; &nbsp;and (xii) protect the integrity of the Website.</p>
            																					<p>
            																						<br> User Information is used and disclosed if required to do so by law or in the good faith and belief that such disclosure is reasonably necessary to respond to notices, court orders, or other legal process. sezplus may disclose User Information to law enforcement officers, third party rights owners, or others that is in its opinion reasonably necessary to enforce the Website’s Terms of Use, this Policy and Terms and Conditions of Sale. sezplus will share some or all of the User Information with another entity should&nbsp; sezplus merge with, or be acquired by that entity or receive investments from that entity.
            																						</p>
            																						<p>&nbsp;</p>
            																						<p>sezplus may disclose aggregated information about the use of the Website. sezplus understands that the User Information is very crucial and is important for the user. The user agrees and acknowledges that the User Information is disclosed or shared with: (i) third party vendors for delivery of the products ordered through the Website, (ii) third party service providers engaged by sezplus to perform the services on sezplus’s behalf, (iii) third party service providers for the purpose of the Website’s security, maintenance, repair or other technical reasons.</p>
            																						<p>
            																							<br> USE OF YOUR INFORMATION
            																							</p>
            																							<p>We use personal information to provide the services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect money; measure consumer interest in our products and services, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection.
            																								<br>
            																									<br> In our efforts to continually improve our product and service offerings, we collect and analyse demographic and profile data about our users' activity on our Website.
            																										<br>
            																											<br> We identify and use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify you and to gather broad demographic information..
            																												<br>
            																													<br> SECURITY PRECAUTIONS
            																													</p>
            																													<p>Our Website has stringent security measures in place to protect the loss, misuse, and alteration of the information under our control. Whenever you change or access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access.</p>
            																													<p>
            																														<br> SECURITY &amp; USER RESTRICTION
            																														</p>
            																														<p>sezplus implements standard measures to protect against unauthorized access to and unlawful interception of the User Information. However, no internet site can fully eliminate security risks. sezplus endeavors to take all measures to protect the security, integrity and confidentiality of the User Information against unauthorized breach and hacking. For the purpose of checking possible vulnerabilities and attacks, sezplus may conduct periodical internal review of data and security measures on the Website. sezplus may use such software as it determines is best for maintaining security. However the internet is not absolutely a secure environment, and the Website cannot ensure or warrant a 100% security of the User Information.</p>
            																														<p>&nbsp;</p>
            																														<p>If any user is provided with any identification code, password or any other piece of information as part of the Website’s security procedure, the user should treat such information as confidential, and the user should not disclose it to any third party including to other users. To prevent third party’s access to the Website the user should sign out from the user account after availing the services through the Website sezplus has the right to disable the identification code or password, whether chosen by any user or allotted by sezplus, at any time, if the user fails to comply with instructions or terms, conditions or policies of sezplus.</p>
            																														<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            																														<p>The user is solely responsible for the activities that occur under the user’s account including the confidentiality of the user’s password and sezplus is not responsible for the same. While using and accessing the Website, the user is responsible for maintaining the confidentiality of the user’s account and for restricting access to the user’s computer or other system or equipments through which the user uses and accesses the Website.</p>
            																														<p>&nbsp;</p>
            																														<p>Notwithstanding anything contained in this Policy or elsewhere,&nbsp;sezplus shall not be held responsible for any loss, damage or misuse of the User Information, if such loss, damage or misuse is attributable to a Force Majeure Event. A&nbsp;
            																															<strong>"Force Majeure Event"</strong>&nbsp;means any event that is beyond the reasonable control of&nbsp;sezplus and includes, without limitation, fire, flood, explosion, acts of God, civil commotion, strikes, lock outs or industrial action of any kind, riots, insurrection, war, acts of government, power failure, sabotage, computer hacking, unauthorised access to computer data and storage device, system failure, virus, attacks, bugs, computer crashes, breach of security and encryption.
            																														</p>
            																														<p>&nbsp;</p>
            																														<p>THIRD PARTY WEBSITES AND LINKS
            																															<br> Website may provide or be linked with other websites and advertisements. sezplus is in no way responsible for the privacy practices or content of such websites. The linked websites or advertisers are not necessarily under the control of sezplus and sezplus expressly disclaims all liability associated with the content and the use of such websites and advertisements. Display of any third party advertisements on the Website shall not be construed as an endorsement or promotion of any products or services by sezplus. The user should read the privacy policy of each and every linked website and any access or use of the linked websites is entirely at the user’s own risk.&nbsp;sezplus is not responsible for any direct, indirect, solicited or unsolicited communication made by any of these linked third party websites or advertisers or their respective agents or representatives, to the users including by telephone, email, mobile phones and facsimile.
            																															</p>
            																															<p>&nbsp;</p>
            																															<p>These linked third-party websites and advertisers may use various technologies to receive the user’s IP address and personal information. The third party advertisers may also use cookies, JavaScript, web beacons and other technologies to gauge the effectiveness of their advertisements and to personalize advertising experience and content. sezplus does not have any control over the cookies or technologies that advertisers or websites may use and the user should contact them directly for more information about their privacy practices and policies.</p>
            																															<p>&nbsp;</p>
            																															<p>Based on the User Information including the nature of products purchased by the user through the Website, sezplus may display personalized third party advertisements on the Website. &nbsp;When the user clicks on the advertisement link, the third party advertisers may assume that the user has met the criteria that was used to personalize the advertisement. The user acknowledges and agrees that in no event sezplus is responsible to the user accessing the services of third party advertisers or other websites.</p>
            																															<p>GENERAL TERMS
            																																<br> This Policy is to be read in conjunction with and shall be deemed to be part of the Website’s Terms of Use and Terms and Conditions of Sale.
            																																</p>
            																																<p>&nbsp;</p>
            																																<p>The User Information resides in sezplus database for a certain period of time even after the user ceases to use or access the Website and in such cases sezplus is not be liable for any usage of the User Information after the user ceases to use or access the Website.</p>
            																																<p>&nbsp;</p>
            																																<p>The Users agree and acknowledge that User Information collated through the Website could be stored and processed in any other country across the world. The users acknowledge that for effective provision of the Website’s services in respective territories including territories outside India, the User Information may be stored or processed by trusted third parties. Whenever the User Information is shared with trusted third parties in countries outside India, sezplus endeavours that the User Information is transferred in accordance with the applicable laws of India.</p>
            																																<p>&nbsp;</p>
            																																<p>The user should be aware that the User Information or other data, the user provides to the Website for availing the services or transacting through the Website could be read, collected, or used by other users or third parties in which case the User Information might be used for sending unsolicited messages or communications for which sezplus is not responsible.</p>
            																																<p>&nbsp;</p>
            																																<p>The user agrees and acknowledges sezplus’s right to utilize the user’s posts, contents, information and other personal data for the purpose of providing services through the Website. The contents on the Website may contain comments, post and reviews posted by the users which may be public and searchable on the internet in which case the user’s comments, post reviews and information and personal data provided to the Website may be viewed by other users and sezplus cannot guarantee that other users or third parties have not made copies of or used the ideas and information that the user has shared on the Website.
            																																	<br>
            																																		<br> CHOICE/OPT OUT
            																																			<strong>
            																																				<br>
            																																				</strong>We provide all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us on behalf of our partners, and from us in general, after setting up an account.
            																																				<br>
            																																					<br> If you want to remove your contact information from all sezplus.com lists and newsletters, please visit&nbsp;
            																																						<a href="http://www.flipkart.com/unsubscribe.php">unsubscribe</a>
            																																						<br> ADVERTISING ON SEZPLUS
            																																						</p>
            																																						<p>We may use third-party advertising companies to serve ads when you visit our Website. These companies may use information (not including your name, address, email
            																																							<br> address, or telephone number) about your visits to this and other websites in order to provide advertisements about &nbsp;services of interest to you.
            																																							</p>
            																																							<p>YOUR CONSENT</p>
            																																							<p>By using the Website and/ or by providing your information, you consent to the collection and use of the information you disclose on the Website in accordance with this Privacy Policy, including but not limited to Your consent for sharing your information as per this privacy policy.
            																																								<br>
            																																									<br> If we decide to change our privacy policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it.
            																																									</p>
            																																									<p>GRIVANCE OFFICER</p>
            																																									<p>In case of any complaints or grievances, the user may contact the Grievance Officer as under:</p>
            																																									<p>Mr. Dibyendu dhara
            																																										<br>
            																																											<a href="mailto:hello@sezplus.com">hello@sezplus.com</a>
            																																											<br> ph:02265260008
            																																												<br>
            																																													<br> QUESTIONS
            																																													</p>
            																																													<p>Please&nbsp;
            																																														<a href="http://www.flipkart.com/s/contact">contact us</a>&nbsp;regarding any questions regarding this statement.
            																																													</p>
            																																													<p>&nbsp;</p>
            																																													<p>
            																																														<strong>GENERAL TERMS OF USE OF WEBSITE</strong>
            																																													</p>
            																																													<p>
            																																														<strong>&nbsp;</strong>
            																																													</p>
            																																													<p>These Website (“
            																																														<strong>Terms</strong>“) are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. These Terms are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology&nbsp;Act, 2000 and the Rules thereunder. These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures.
            																																														<br>
            																																															<br> DEFINITIONS
            																																																<br> In this document, unless the context otherwise requires, the following word and phrases shall have the meanings ascribed to them hereunder:
            																																																</p>
            																																																<p>
            																																																	<strong>Affiliate Site(s)</strong>" shall mean webpages, websites, mobile sites, mobile application and online platforms
            																																																	<strong>&nbsp;</strong>of sezplus, rk sezplus services pvt ltd.
            																																																</p>
            																																																<p>
            																																																	<strong>Customer</strong>" means the registered user of&nbsp;sezplus.com
            																																																</p>
            																																																<p>
            																																																	<strong>sezplus account"</strong>&nbsp;shall mean the account created by the Customer using Single-Sign-On Services provided by sezplus which would give the Customer access to Affiliate Site(s) and Merchant Site(s).
            																																																</p>
            																																																<p>
            																																																	<strong>Merchant(s)"</strong>&nbsp;shall mean seller(s), retailers or e-commerce marketplaces or such other business entities which allow Customers to use sezplus account, mobile site, mobile application or establishments.
            																																																</p>
            																																																<p>
            																																																	<strong>Mobile Application(s)"</strong>&nbsp;shall mean the software application(s) which inter alia, enables sezplus account through the mobile-device.
            																																																</p>
            																																																<p>
            																																																	<strong>Single-Sign-On Services" or "Services"</strong>&nbsp;shall mean a session/user authentication process that permits a user to enter his/her name or mobile number or e-mail address or any combination thereof and password in order to access Affiliate Site(s).
            																																																</p>
            																																																<p>
            																																																	<strong>Terms and Conditions"&nbsp;</strong>shall mean these terms and conditions.
            																																																</p>
            																																																<p>
            																																																	<strong>Website"</strong>&nbsp;shall mean website having the domain
            																																																	<a href="https://www.sezplus.com">https://www.sezplus.com</a> mobile site, Mobile Application(s) or online interphases, through which sezplus shall among other things enable Single-Sign-On Services.
            																																																</p>
            																																																<p>
            																																																	<strong>&nbsp;</strong>
            																																																</p>
            																																																<p>&nbsp;INTRODUCTION
            																																																	<br> The website sezplus.com ("
            																																																		<strong>Website</strong>") is operated by rk sezplus services pvt.ltd., a company incorporated under the Companies Act, 2013 ("
            																																																		<strong>sezplus</strong>") having its registered office at saikrupa chwl, Quamar baug, near Hema industry, Meghwadi, Jogeswari (e) Mumbai 400060 &nbsp;Use of the Website and its services is governed by these Terms of Use (“
            																																																		<strong>Terms</strong>”).
            																																																	</p>
            																																																	<p>By using the Website, users signify they have carefully read, understood and agree to be bound by these Terms. When users transact or browse through the Website or avail any service provided by the Website, in present or future, users accept and agree to be bound by these Terms, policies, guidelines and conditions of sezplus.com’s services.</p>
            																																																	<p>These Terms could be changed, altered, edited, amended, modified, reviewed, revised or substituted by sezplus at any time with or without prior notice and users are requested to read the Terms before using or accessing the Website. &nbsp;
            																																																		<br>
            																																																			<br> COMMUNICATION
            																																																			</p>
            																																																			<p>When You use the Website or send emails or other data, information or&nbsp;communication to us, You agree and understand that You are communicating&nbsp;with Us through electronic records and You consent to receive communications&nbsp;via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication,&nbsp;electronic or otherwise.</p>
            																																																			<p>The Website is a platform that Users utilize to meet and interact with one another&nbsp;for their transactions. sezplus is not and cannot be a party to or control in any&nbsp;manner any transaction between the Website's Users.
            																																																				<br>
            																																																					<br> HENCEFORWARD
            																																																					</p>
            																																																					<p>1. All commercial/contractual terms are offered by and agreed to between Buyers&nbsp;and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode&nbsp;of delivery, warranties related to products and services and after sales services related to products and services. sezplus does not have any control or does not&nbsp;determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers are by the Seller/Brand and not by sezplus.</p>
            																																																					<p>2. Sezplus does not make any representation or Warranty as to specifics (such&nbsp;as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Website. Sezplus does not implicitly or&nbsp;explicitly support or endorse the sale or purchase of any products or services on&nbsp;the Website. Sezplus accepts no liability for any errors or omissions, whether on&nbsp;behalf of itself or third parties.</p>
            																																																					<p>3. Sezplus is not responsible for any non-performance or breach of any contract&nbsp;entered into between Buyers and Sellers. Sezplus cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded&nbsp;on the Website. Sezplus shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.</p>
            																																																					<p>4. Sezplus does not at any point of time during any transaction between Buyer&nbsp;and Seller on the Website come into or take possession of any of the products or&nbsp;services offered by Seller nor does it at any point gain title to or have any rights&nbsp;or claims over the products or services offered by Seller to Buyer.</p>
            																																																					<p>&nbsp;
            																																																						<br> PLATFORM SERVICES
            																																																						</p>
            																																																						<p>The Website is a platform that users utilize to communicate and transact with one another. Sezplus is not and cannot be a party to or control in any&nbsp;manner any transaction between users of the Website. The purchase of products on the Website are governed by the terms and condition of sale.&nbsp;</p>
            																																																						<p>The Website is only a platform that can be used by users to reach a larger&nbsp;base to buy and sell products. sezplus is only providing a platform for&nbsp;communication and the contract for sale of the products&nbsp;shall be a strictly bipartite contract between the buyer and the seller. At no time shall sezplus hold any right, title or interest over the products or&nbsp;have any obligations or liabilities in respect of such bipartite contract entered&nbsp;into between the buyer and seller.&nbsp;</p>
            																																																						<p>Users may upload and display the images and information of their products offered for sale on the Website’s online platform. Such display of the user’s products or related information on the Website in no manner can be treated or construed as an endorsement or advertisement of such products by sezplus. &nbsp;&nbsp;&nbsp;</p>
            																																																						<p>Provision of a specific service through the online platform of the Website will be subject to users agreeing and consenting to certain additional terms, rules, policies, procedures, guidelines, disclaimers, notices or otherwise, if any, as applicable to such service (“
            																																																							<strong>Additional Terms</strong>“) and if there is any conflict between the Terms of Use and the Additional Terms, the Additional Terms shall take precedence in relation to that specific service.
            																																																							<br>
            																																																								<br> &nbsp;ELIGIBILITY
            																																																									<br> The user should have completed 18 years of age and be competent to enter into a contract under Indian contract law. Any user under 18 years of age who is intending to avail the services of the Website should do so through his or her legal guardian&nbsp; in accordance with applicable law.&nbsp;
            																																																									</p>
            																																																									<p>If any person is using the Website on behalf of any corporation, company, institution, association or other entity, the person should be authorized by such corporation, company, institution, association or other entity to use and access the Website.&nbsp;</p>
            																																																									<p>&nbsp;Sezplus reserves the right to refuse access to use the services offered at the Website to new users or to terminate access granted to existing users at any time without according any reasons for doing so.
            																																																										<br>
            																																																											<br>
            																																																												<br> USE OF THE WEBSITE
            																																																													<br> You agree, undertake and confirm that Your use of Website shall be strictly&nbsp;governed by the following binding principles:
            																																																													</p>
            																																																													<p>1. You shall not host, display, upload, modify, publish, transmit, update or share&nbsp;any information which:</p>
            																																																													<p>(a) belongs to another person and to which You does not have any right to;</p>
            																																																													<p>(b) is grossly harmful, harassing, blasphemous, defamatory, obscene,&nbsp;pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or&nbsp;racially, ethnically objectionable, disparaging, relating or encouraging money&nbsp;laundering or gambling, or otherwise unlawful in any manner whatever;&nbsp;or unlawfully threatening or unlawfully harassing including but not limited&nbsp;to "indecent representation of women" within the meaning of the Indecent&nbsp;Representation of Women (Prohibition) Act, 1986;</p>
            																																																													<p>(c) is misleading in any way;</p>
            																																																													<p>(d) is patently offensive to the online community, such as sexually explicit&nbsp;content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred&nbsp;or physical harm of any kind against any group or individual;</p>
            																																																													<p>(e) harasses or advocates harassment of another person;</p>
            																																																													<p>(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass&nbsp;mailing or "spamming";</p>
            																																																													<p>(g) promotes illegal activities or conduct that is abusive, threatening, obscene,&nbsp;defamatory or libellous;</p>
            																																																													<p>(h) infringes upon or violates any third party's rights [including, but not limited&nbsp;to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or&nbsp;phone number) or rights of publicity];</p>
            																																																													<p>(i) promotes an illegal or unauthorized copy of another person's copyrighted work&nbsp;(see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer&nbsp;programs or links to them, providing information to circumvent manufacture-installed copy-protect devices,</p>
            																																																													<p>(j) contains restricted or password-only access pages, or hidden pages or images&nbsp;(those not linked to or from another accessible page);</p>
            																																																													<p>(k) provides material that exploits people in a sexual, violent or otherwise&nbsp;inappropriate manner or solicits personal information from anyone;</p>
            																																																													<p>(l) provides instructional information about illegal activities such as making or&nbsp;buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</p>
            																																																													<p>(m) contains video, photographs, or images of another person (with a minor or&nbsp;an adult).</p>
            																																																													<p>(n) tries to gain unauthorized access or exceeds the scope of authorized access&nbsp;to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal&nbsp;identifying information for commercial or unlawful purposes from other users;</p>
            																																																													<p>(o) engages in commercial activities and/or sales without Our prior written&nbsp;consent such as contests, sweepstakes, barter, advertising and pyramid schemes,&nbsp;or the buying or selling of "virtual" products related to the Website. Throughout&nbsp;this Terms of Use, Sezplus 's prior written consent means a communication&nbsp;coming from Sezplus 's Legal Department, specifically in response to Your&nbsp;request, and specifically addressing the activity or conduct for which You seek&nbsp; authorization;</p>
            																																																													<p>(p) solicits gambling or engages in any gambling activity which We, in Our sole&nbsp;discretion, believes is or could be construed as being illegal;</p>
            																																																													<p>(q) interferes with another USER's use and enjoyment of the Website or any&nbsp;other individual's User and enjoyment of similar services;</p>
            																																																													<p>(r) refers to any website or URL that, in Our sole discretion, contains material&nbsp;that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</p>
            																																																													<p>(s) harm minors in any way;</p>
            																																																													<p>(t) infringes any patent, trademark, copyright or other proprietary rights or third&nbsp;party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;</p>
            																																																													<p>(u) violates any law for the time being in force;</p>
            																																																													<p>(v) deceives or misleads the addressee/ users about the origin of such messages&nbsp;or communicates any information which is grossly offensive or menacing in nature.</p>
            																																																													<p>(w) impersonate another person;</p>
            																																																													<p>(x) contains software viruses or any other computer code, files or programs&nbsp;designed to interrupt, destroy or limit the functionality of any computer resource;&nbsp;or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or&nbsp;other computer programming routines that may damage, detrimentally interfere&nbsp;with, diminish value of, surreptitiously intercept or expropriate any system, data&nbsp;or personal information;</p>
            																																																													<p>(y) threatens the unity, integrity, defence, security or sovereignty of India,&nbsp;friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or&nbsp;is insulting any other nation.</p>
            																																																													<p>(z) shall not be false, inaccurate or misleading;</p>
            																																																													<p>(aa) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to&nbsp;trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the&nbsp;time being in force.</p>
            																																																													<p>(ab) shall not create liability for Us or cause Us to lose (in whole or in part) the&nbsp;services of Our internet service provider ("ISPs") or other suppliers;</p>
            																																																													<p>&nbsp;
            																																																														<br> USER ACCOUNT
            																																																															<br> The user may browse the Website without registering with sezplus.com, The user has to set up an account with the Website before availing any online services provided through the Website. &nbsp;The user can create an account by entering an email address and password or by using any permitted social media website account to sign in ("
            																																																																<strong>Account Information</strong>"). The email address provided is not verified by sezplus.com and hence, it is advisable for the user to provide a valid email address. The Website will set-up an account and email the details of the account to the user at the email address provided. A user can then access the account on the Website. A user can also create and update an account through Customer Support.
            																																																															</p>
            																																																															<p>A user can create one user account only and no user is permitted to transfer or interchange the User Account. The list of user information required to be provided by the user, the manner of usage, protection and confidentiality of user information and account information are more specifically dealt under the Website’s Privacy Policy and the users are requested to read in detail the Privacy Policy before sharing user information or creating an account.
            																																																																<br>
            																																																																	<br> CONTENT POSTED ON SITE
            																																																																		<br> All text, graphics, user interfaces, visual interfaces, photographs, trademarks,&nbsp;logos, sounds, music and artwork (collectively, "Content"), is a third party&nbsp;user generated content and Sezplus has no control over such third party user&nbsp;generated content as Sezplus is merely an intermediary for the purposes of this&nbsp;Terms of Use. Except as expressly provided in these Terms of Use, no part of the Website&nbsp;and no Content may be copied, reproduced, republished, uploaded, posted,&nbsp;publicly displayed, encoded, translated, transmitted or distributed in any way&nbsp;(including "mirroring") to any other computer, server, Website or other medium&nbsp;for publication or distribution or for any commercial enterprise, without Sezplus 's&nbsp;express prior written consent. You may use information on the products and services purposely made available&nbsp;on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such&nbsp;information only for your personal, non-commercial informational purpose and&nbsp;do not copy or post such information on any networked computer or broadcast it&nbsp;in any media, (3) make no modifications to any such information, and (4) do not&nbsp;make any additional representations or warranties relating to such documents. shall be responsible for any notes, messages, emails, billboard postings,&nbsp;photos, drawings, profiles, opinions, ideas, images, videos, audio files&nbsp;or other materials or information posted or transmitted to the Website&nbsp;(collectively, "Content"). Such Content will become Our property and You grant&nbsp;Us the worldwide, perpetual and transferable rights in such Content. We shall&nbsp;be entitled to, consistent with Our Privacy Policy as adopted in accordance&nbsp;with applicable law, use the Content or any of its elements for any type of use&nbsp;forever, including but not limited to promotional and advertising purposes and&nbsp;in any media whether now known or hereafter devised, including the creation of&nbsp;derivative works that may include the Content You provide. You agree that any&nbsp;Content You post may be used by us, consistent with Our Privacy Policy and Rules&nbsp;of Conduct on Site as mentioned herein, and You are not entitled to any payment&nbsp;or other compensation for such use.
            																																																																			<span style="text-decoration: underline;">
            																																																																				<br>
            																																																																				</span>
            																																																																				<br> USE OF CONTENT
            																																																																				</p>
            																																																																				<p>Any content that the user posts or material it submits, the user grants Sezplus and its affiliates and associates a non-exclusive, royalty-free, irrevocable, perpetual and fully sub-licensable rights to use, reproduce, publish, distribute and display such content throughout the world in any mode medium or manner now known or developed in future; and the right to use the name that the user submits in connection with such content, if the user chooses.&nbsp;</p>
            																																																																				<p>The user agrees that the rights the user grants as above are irrevocable during the entire period of protection of the user’s intellectual property rights associated with such content and material. The user agrees to waive the user’s right to be identified as the author of such&nbsp;content and materials and the user’s right to object to derogatory treatment of such content or material. The user agrees to perform all further acts and execute deeds and documents necessary to perfect the above rights granted by the user to Sezplus.&nbsp;</p>
            																																																																				<p>The user represents and warrants that the user owns or otherwise controls all of the rights to the content and material that the user posts or that the user otherwise provides on or through the Website; that, as at the date that the content or material is submitted to the Website: (i) the content and material is accurate; (ii) use of the content and material does not breach any applicable Indian law or the Website’s policies or guidelines or Additional Terms (iii) the content and material do not breach these Terms and Privacy Policy.</p>
            																																																																				<p>THIRD PARTY WEBSITE
            																																																																					<br> The Website may contain links to other websites and the Website are not in any way responsible for the terms of use or content of such websites and expressly disclaims all liability associated with the content and use of these websites.&nbsp;The linked websites are not under the control of Sezplus.com and users are encouraged to read the terms of use and privacy policy of each and every linked website. If users decide to access any of the third-party websites linked to the Website, it is at the risk of the users to access and use such linked websites and Sezplus shall not be responsible in any manner whatsoever
            																																																																						<br>
            																																																																							<br> SELLING
            																																																																							</p>
            																																																																							<p>As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfilment of sales.
            																																																																								<br>
            																																																																									<br> The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website. Sezplus reserves the right to delete such multiple listings of the same product listed by you in various categories.
            																																																																									</p>
            																																																																									<p>
            																																																																										<strong>Payment</strong>
            																																																																									</p>
            																																																																									<p>While availing any of the payment method/s available on the Website, we will&nbsp;not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:</p>
            																																																																									<ol>
            																																																																										<li>Lack of authorization for any transaction/s, or</li>
            																																																																										<li>Exceeding the preset limit mutually agreed by You and between&nbsp;"Bank/s", or</li>
            																																																																										<li>Any payment issues arising out of the transaction, or</li>
            																																																																										<li>Decline of transaction for any other reason/s</li>
            																																																																									</ol>
            																																																																									<p>&nbsp;
            																																																																										<span style="text-decoration: underline;">Product Description</span>
            																																																																									</p>
            																																																																									<p>Sezplus we do not warrant that Product description or other content of this&nbsp;Website is accurate, complete, reliable, current, or error-free and assumes no&nbsp;liability in this regard.
            																																																																										<br>
            																																																																											<br> LIMITATION OF LIABILITY
            																																																																												<br> In no event shall sezplus be liable for any special incidental indirect or consequential damages of any kind in connection with these terms of use, even if user has been informed in advance of the possibility of such damages.
            																																																																													<br>
            																																																																														<br> INDEMNITY
            																																																																														</p>
            																																																																														<p>Users &nbsp;agree to indemnify and hold harmless Sezplus including affiliates, associates and their respective owners, directors, officers, agents, shareholders and partners from and against all actions, proceedings, claims, losses, damages and costs (including attorney fees) and other expenses suffered or incurred due to or attributable to or arising out of (i) violation of any applicable law (ii) breach of any representations, warranties or covenants of the user (iii) breach of the policies, guidelines and conditions of Sezplus’s service or Additional Terms or these Terms or Privacy Policy (including any modifications or additional notifications or instructions); (iv) infringement of any third party rights. This Clause survives the termination of these Terms.
            																																																																															<br> TERMINATION
            																																																																															</p>
            																																																																															<p>Sezplus reserves the right to terminate the services provided to any user without prior notice in the event of any default committed by user including but not limited to the breach of any applicable law, policies, guidelines and conditions of Sezplus service or Additional Terms or these Terms or the Privacy Policy (including any modifications or additional notifications or instructions).&nbsp; On such termination, the user’s information and other details shall be black listed by the Website and shall be taken into consideration whenever necessary.&nbsp;</p>
            																																																																															<p>Sezplus will terminate the services provided to any user if it is required under any applicable law.&nbsp; Without prejudice, Sezplus reserves its right to terminate the services if such provision of services to the users is not economically viable for Sezplus. Users may choose to discontinue availing services and facilities provided through the Website by closing the user account with the Website. &nbsp;</p>
            																																																																															<p>On termination of the user account, the user is not eligible to purchase or sell products through the Website. Once the user’s account is terminated for any reason whatsoever, the contents, reviews, comments or other material posted on the Website by the user shall be removed by Sezplus.</p>
            																																																																															<p>Post termination of the services provided to the user through the Website, the user’s personal information would reside in the Website’s database for a certain period of time. It is also clarified that certain terms and conditions of the policies, guidelines and conditions of Sezplus’s service or Additional Terms or these Terms and the Privacy Policy continue to be binding on the user and if any user by default or otherwise is found using or dealing with the Website post termination of the service provided through the Website, the user shall be prosecuted by Sezplus. The user shall be also liable to compensate Sezplus for any unauthorized use of the Website.</p>
            																																																																															<p>
            																																																																																<br> MISCELLANEOUS&nbsp;
            																																																																																</p>
            																																																																																<p>Each of the provisions in&nbsp; these Terms are sever able and distinct from the others and if at any time one or more such provisions is or becomes invalid, illegal or unenforceable, the validity, legality and enforce ability of the remaining provisions of these Terms shall not in any way be affected or impaired thereby.&nbsp;&nbsp;&nbsp;</p>
            																																																																																<p>Any user may contact SEZPLUS at the following address:&nbsp;</p>
            																																																																																<p>To</p>
            																																																																																<p>Grievance Officer</p>
            																																																																																<p>E-Mail:
            																																																																																	<a href="mailto:support@sezplus.com">support@sezplus.com</a>
            																																																																																</p>
            																																																																																<p>&nbsp;</p>
            																																																																																<p>GOVERNING LAW AND JURISDICTION</p>
            																																																																																<p>The terms and conditions of this agreement shall be governed by Indian law and the courts in Mumbai shall only have exclusive jurisdiction to resolve any disputes.</p>
            																																																																															</p>
          </div>
        </div>
      </div>
      <?php echo $content_bottom; ?></div>
    <?php echo $column_right; ?></div>
</div>
<?php echo $footer; ?>
